version: "3.9"

services:

  sqlserver-a:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Uta2026!Strong"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqldata-a:/var/opt/mssql
    networks:
      - uta-network

  sqlserver-b:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Uta2026!Strong"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - sqldata-b:/var/opt/mssql
    networks:
      - uta-network

  sqlserver-c:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Uta2026!Strong"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1435:1433"
    volumes:
      - sqldata-c:/var/opt/mssql
    networks:
      - uta-network

  microservicio-a:
    build:
      context: ./src/MicroservicioA
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver-a
    networks:
      - uta-network
    restart: on-failure

  microservicio-b:
    build:
      context: ./src/MicroservicioB
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver-b
      - microservicio-c
    networks:
      - uta-network
    restart: on-failure

  microservicio-c:
    build:
      context: ./src/MicroservicioC
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver-c
    networks:
      - uta-network
    restart: on-failure

  api-gateway:
    build:
      context: ./src/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - microservicio-a
      - microservicio-b
      - microservicio-c
    networks:
      - uta-network
    restart: on-failure

networks:
  uta-network:
    driver: bridge

volumes:
  sqldata-a:
  sqldata-b:
  sqldata-c: