// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using MicroservicioC.Data;

#nullable disable

namespace MicroservicioC.Migrations
{
    [DbContext(typeof(ZonaDbContext))]
    partial class ZonaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroservicioC.Models.Zona", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("ActualizadaEn").HasColumnType("datetime2");
                b.Property<string>("Color").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreadaEn").HasColumnType("datetime2");
                b.Property<string>("Nombre").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Poligono").IsRequired().HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.HasIndex("Nombre").IsUnique();
                b.ToTable("Zonas");
            });
#pragma warning restore 612, 618
        }
    }
}
