// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using MicroservicioA.Data;

#nullable disable

namespace MicroservicioA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroservicioA.Models.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Correo")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("CreadoEn")
                    .HasColumnType("datetime2");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("IntentosFallidos")
                    .HasColumnType("int");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Rol")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("UltimoAcceso")
                    .HasColumnType("datetime2");

                b.Property<string>("ZonaAsignada")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.HasIndex("Correo").IsUnique();
                b.ToTable("Usuarios");
            });
#pragma warning restore 612, 618
        }
    }
}
